#!/bin/sh +x

cd $HOME/heron/incubator-heron

echo "Compiling heron...."
bazel build --config=ubuntu heron/...
if [ $? -ne 0 ]
then
   echo "Failed to build heron/..."
   exit 1
fi

echo "Building binpkgs...."
bazel build --config=ubuntu scripts/packages:binpkgs
if [ $? -ne 0 ]
then
    echo "Faile to build binpkgs"
    exit 2
fi

echo "Install heron locally...."
bazel-bin/scripts/packages/heron-install.sh --user

